# Generated by Django 4.1.5 on 2023-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0001_bio_proj_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=300)),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_inquiry', models.TextField(max_length=500)),
                ('inquiry_date', models.DateTimeField(auto_now_add=True)),
                ('inquiry_accomplished', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Me',
                'ordering': ('inquiry_date',),
            },
        ),
    ]
