# Generated by Django 4.1.5 on 2023-01-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0002_contact_me_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_img',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
