# Generated by Django 4.1.5 on 2023-01-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0002_contact_me_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='bio_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='biography',
            name='curr_proj_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='biography',
            name='curr_proj_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='biography',
            name='quick_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
