# Generated by Django 4.1.5 on 2023-01-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0003_updated_blanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_img_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
