# Generated by Django 4.1.5 on 2023-06-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0003_updated_blanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('quick_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='biography',
            name='quick_description',
        ),
        migrations.CreateModel(
            name='SocialsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
                ('info_link', models.URLField()),
                ('info_icon', models.CharField(max_length=20)),
                ('info_color', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jdwebport_app.profile')),
            ],
        ),
    ]
