# Generated by Django 4.1.5 on 2023-06-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0004_biography_socials_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biography',
            name='quote',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialsprofile',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='jdwebport_app.profile'),
        ),
    ]
