# Generated by Django 4.1.5 on 2023-06-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0006_bio_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='jdwebport_app.profile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_notes', models.TextField(blank=True, max_length=500, null=True)),
                ('final_notes', models.TextField(blank=True, max_length=500, null=True)),
                ('project_notes', models.TextField(blank=True, max_length=700, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jdwebport_app.project')),
                ('resume_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jdwebport_app.resumeprojects')),
            ],
        ),
    ]
