# Generated by Django 4.1.5 on 2023-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0008_feedback_contactme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrProj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_title', models.CharField(max_length=255)),
                ('focus_date', models.DateField()),
                ('focus_info', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='biography',
            name='curr_proj_description',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='curr_proj_entry_date',
        ),
        migrations.RemoveField(
            model_name='biography',
            name='curr_proj_name',
        ),
    ]
