# Generated by Django 4.1.5 on 2023-06-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0009_curr_proj_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_learnings',
            field=models.TextField(default=1, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='proj_purpose',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='proj_tools',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
