# Generated by Django 4.1.5 on 2023-07-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0011_curr_proj_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnotes',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_notes', to='jdwebport_app.project'),
        ),
    ]
