# Generated by Django 4.1.5 on 2023-07-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0012_alter_projectnotes_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeprojects',
            old_name='slug',
            new_name='resume_slug',
        ),
        migrations.AlterField(
            model_name='projectnotes',
            name='project_notes',
            field=models.TextField(default=1, max_length=700),
            preserve_default=False,
        ),
    ]
