# Generated by Django 4.1.5 on 2023-07-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0013_rename_slug_resumeprojects_resume_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeawardsandachievements',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
