# Generated by Django 4.1.5 on 2023-08-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0014_alter_resumeawardsandachievements_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectnotes',
            name='resume_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_proj_notes', to='jdwebport_app.resumeprojects'),
        ),
    ]
