# Generated by Django 4.1.5 on 2023-08-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0015_alter_projectnotes_resume_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='currproj',
            name='curr_proj_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='resumeprojects',
            name='resume_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
