# Generated by Django 4.1.5 on 2023-08-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0016_updated_curr_resume_proj'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('section_info', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BiographySectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_img', models.ImageField(upload_to='section_img/')),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='jdwebport_app.biography')),
            ],
        ),
    ]
