# Generated by Django 4.1.5 on 2023-08-14 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0017_bio_section_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='biographysection',
            name='biography',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='jdwebport_app.biography'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biographysectionimage',
            name='section_img_slug',
            field=models.SlugField(default='img_testing'),
            preserve_default=False,
        ),
    ]
