# Generated by Django 4.1.5 on 2023-08-14 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0018_bio_fkey_img_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biographysectionimage',
            name='biography',
        ),
        migrations.AddField(
            model_name='biographysection',
            name='section_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='biographysectionimage',
            name='biography_section',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='jdwebport_app.biographysection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biographysectionimage',
            name='section_img_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
