# Generated by Django 4.1.5 on 2023-08-18 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0019_bio_section_slug_img_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographysection',
            name='biography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_section', to='jdwebport_app.biography'),
        ),
        migrations.AlterField(
            model_name='biographysectionimage',
            name='biography_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_imgs', to='jdwebport_app.biographysection'),
        ),
    ]
