# Generated by Django 4.1.5 on 2023-08-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0021_updated_contact_me_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeawardsandachievements',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_award_achievement', to='jdwebport_app.resume'),
        ),
        migrations.AlterField(
            model_name='resumeprojects',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_project', to='jdwebport_app.resume'),
        ),
    ]
