# Generated by Django 4.1.5 on 2023-08-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0022_related_names_resume_proj_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=500)),
                ('resume_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_proj_details', to='jdwebport_app.resumeprojects')),
            ],
        ),
    ]
