# Generated by Django 4.1.5 on 2023-09-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdwebport_app', '0024_added_proj_brief_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographysectionimage',
            name='section_img',
            field=models.ImageField(upload_to='section_imgs/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image_slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('project_image', models.ImageField(upload_to='project_imgs/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_imgs', to='jdwebport_app.project')),
            ],
        ),
    ]
